# Supported funding model platforms for GitHub Sponsors and funding button
github: sarathcodes
buy_me_a_coffee: sarathcodes
ko_fi: sarathcodes
custom: ['https://www.buymeacoffee.com/sarathcodes', 'https://github.com/sponsors/sarathcodes']
